language: node_js
node_js:
- '6'
- node
notifications:
  webhooks:
    urls:
    - http://45.55.190.196:3000/travisci
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_4f5280b68f7e_key -iv $encrypted_4f5280b68f7e_iv
  -in deploy_rsa.enc -out ../../../deploy_rsa -d
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm i -g npm@^3
script:
- npm run lint
- npm test
- npm run build:docker
sudo: required
