language: node_js
node_js:
  - "6"
  - "node"
notifications:
  webhooks:
    urls:
      - http://45.55.190.196:3000/travisci
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never   # default: never
    on_cancel: never # default: always
    on_error: never # default: always
services:
  - docker
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  # Updating NPM to relevant version >= 3 on Node.JS LTS
  - npm i -g npm@^3
script:
  - npm run lint
  - npm test
  - npm run build:docker
sudo: required
