language: node_js
dist: xenial
node_js:
- "8"
services:
- docker
- xvfb
before_install:
  # Updating NPM to relevant version >= 3 on Node.JS LTS
- npm i -g brfs
script:
- npm run lint
- npm run build-prod
- npm run test
sudo: required
addons:
  apt:
    packages:
    - sshpass
    - google-chrome-stable
after_success:
- mv dist/ngx-amrs $TRAVIS_BRANCH
- tar -czf build.tgz $TRAVIS_BRANCH
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp -o stricthostkeychecking=no build.tgz $DEPLOY_USER@$DEPLOY_HOST:./
- sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST ./deploy-build.sh
